### ISSUE TITLE
Run terminal 3 in senario

### ISSUE THREAD

**Issue by trand2k** [evshary/zenoh_carla_bridge#18]
Hi author, 
I can see this file , how to run terminal 3 ?
![Uploading Screenshot from 2023-11-15 08-50-07.png…]()

**Comment by trand2k** [comment]
![Screenshot from 2023-11-15 08-50-07](https://github.com/evshary/zenoh_carla_bridge/assets/53207542/8411e6ab-33de-4601-8ed6-10d0ba4726eb)

**Comment by evshary** [comment]
You need to build zenoh-bridge-dds first
https://github.com/eclipse-zenoh/zenoh-plugin-dds

**Comment by evshary** [comment]
Since it's inactive for a while, let me close the issue.
Feel free to open if you have further questions.
